image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
build_image:
  stage: deploy
  before_script:
    - docker info
    - cp config.py.dist config.py
    - docker build -terrbot ./
    - pip install awscli
  script:
    - docker tag jon-knows-rasa electricmaxxx/jon-knows-rasa
    - registry.gitlab.com/electricmaxxx/jon-knows-rasa
