intents:
    - who_knows_topic
    - claim_to_know_topic
    - claim_to_know_topic_in_category
    - forgott_topic
    - topics_in_category
    - greet
    - goodbye

entities:
    - category
    - topic
    - score

slots:
    user:
        type: text
    category:
      type: text
    topic:
        type: text
    score:
        type: categorical
        values:
            - 1
            - 2
            - 3
            - 4

templates:
    utter_greet:
        - Ich habe keine ahnung
        - Sein oder nicht sein - wer soll denn sowas wissen?
    utter_goodbye:
        - Bye
    utter_get_who_knows_topic:
        - Um welches Thema geht es?
    utter_get_who_knows_category:
        -  "In welche Kategorie würdest du es einsortieren?"
    utter_get_claim_to_know_topic:
        - Um welches Thema geht es?
    utter_get_claim_to_know_category:
        -  "In welche Kategorie würdest du es einsortieren?"

actions:
    - utter_greet
    - utter_goodbye
    - utter_get_who_knows_category
    - utter_get_who_knows_topic
    - utter_get_claim_to_know_category
    - utter_get_claim_to_know_topic
    - actions.ActionWhoKnowsTopic
    - actions.ActionClaimToKnowTopic
    - actions.ActionIForgot
    - actions.ActionTopicsInCategory