intents:
    - who_knows
    - claim_to_know
    - forgotten
    - greet

entities:
    - category
    - topic
    - score

slots:
    category:
        type: text
    topic:
        type: text
    score:
        type: text

templates:
    utter_greet:
        - Ich habe keine ahnung
        - Sein oder nicht sein - wer soll denn sowas wissen?
    utter_get_who_knows_category:
        - In welche Kategorie würdest du es einsortieren
        - Wo gehört es dazu?
    utter_get_who_knows_topic:
        - Um welches Thema geht es?
    utter_get_claim_to_know_category:
        - In welche Kategorie würdest du es einsortieren
        - Wo gehört es dazu?
    utter_get_claim_to_know_topic:
        - Um welches Thema geht es?

actions:
    - utter_greet
    - utter_get_who_knows_category
    - utter_get_who_knows_topic
    - utter_get_claim_to_know_category
    - utter_get_claim_to_know_topic
    - actions.ActionWhoKnows
    - actions.ActionClaimToKnow
    - actions.ActionIForgot