intents:
    - who_knows_topic
    - claim_to_know_topic
    - forgott_topic
    - topics_in_category
    - greet
    - goodbye

entities:
    - category
    - topic
    - score

slots:
    category:
      type: categorical
      values:
        - "None"
        - "Tools"
        - "Technologien"
        - "Plattformen"
        - "Sprachen & Frameworks"
    topic:
        type: text
    score:
        type: categorical
        values:
            - 1
            - 2
            - 3
            - 4

templates:
    utter_greet:
        - Ich habe keine ahnung
        - Sein oder nicht sein - wer soll denn sowas wissen?
    utter_goodbye:
        - Bye
    utter_get_who_knows_topic:
        - Um welches Thema geht es?
    utter_get_who_knows_category:
        - text: "In welche Kategorie würdest du es einsortieren?"
          buttons:
            - title: "Sprachen & Frameworks"
              payload: "Sprachen & Frameworks"
            - title: "Tools"
              payload: "Tools"
            - title: "Technologien"
              payload: "Technologien"
            - title: "Plattformen"
              payload: "Plattformen"
    utter_get_claim_to_know_topic:
        - Um welches Thema geht es?
    utter_get_claim_to_know_category:
        - text: "In welche Kategorie würdest du es einsortieren?"
          buttons:
            - title: "Sprachen & Frameworks"
              payload: "Sprachen & Frameworks"
            - title: "Tools"
              payload: "Tools"
            - title: "Technologien"
              payload: "Technologien"
            - title: "Plattformen"
              payload: "Plattformen" 

actions:
    - utter_greet
    - utter_goodbye
    - utter_get_who_knows_category
    - utter_get_who_knows_topic
    - utter_get_claim_to_know_category
    - utter_get_claim_to_know_topic
    - actions.ActionWhoKnows
    - actions.ActionClaimToKnow
    - actions.ActionIForgot
    - actions.ActionTopicsInCategory